# See: https://gohugo.io/content-management/multilingual/#configure-languages

[en]
  languageName = "English"
  languageCode = "en"
  #languageCodeCountry = "xx"              # custom
  languageFlag = "ğŸ‡¬ğŸ‡§"                     # custom
  timeZone = "Etc/UTC"
  #tzOffset = "12h"                        # custom
  tzAbbr = "UTC"                          # custom
  tzAbbrTitle = "Universal Time Coordinated"                        # custom
  weight = 110
  [[en.menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2
  [[en.menu.main]]
    identifier = "archives"
    name = "Archives"
    url = "/archives/"
    weight = 3

#[en-ph]
#  languageName = "English (PH)"
#  languageCode = "en-PH"
#  languageCodeCountry = "ph"              # custom
#  languageFlag = "ğŸ‡µğŸ‡­"                     # custom
#  timeZone = "Asia/Manila"
#  tzOffset = "8h"                        # custom
#  tzAbbr = "ACT"                          # custom
#  tzAbbrTitle = "Asean Common Time"                        # custom
#  weight = 111
#  [[en-ph.menu.main]]
#    identifier = "about"
#    name = "About"
#    url = "/about/"
#    weight = 2
#  [[en-ph.menu.main]]
#    identifier = "archives"
#    name = "Archives"
#    url = "/archives/"
#    weight = 3

#[fil]
  #languageName = "Filipino"
  #languageCode = "fil"
  #languageCodeCountry = "ph"              # custom
  #languageFlag = "ğŸ‡µğŸ‡­"                     # custom
  #timeZone = "Asia/Manila"
  #tzOffset = "8h"                        # custom
  #tzAbbr = "ACT"                          # custom
  #tzAbbrTitle = "Asean Common Time"                        # custom
  #weight = 120
  #title = ""
  #[fil.params]
    #description = ""     # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD

#[tl-tglg]
  #languageName = "Tagalog Baybayin"
  #languageCode = "tl-Tglg"
  #languageCodeCountry = "ph"              # custom
  #languageFlag = "ğŸ‡µğŸ‡­"                     # custom
  #timeZone = "Asia/Manila"
  #tzOffset = "8h"                        # custom
  #tzAbbr = "ACT"                          # custom
  #tzAbbrTitle = "Asean Common Time"                        # custom
  #title = ""
  #[tl.tglg.params]
    #description = ""     # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD

#[zh-hant]
  #languageName = "ä¸­æ–‡ï¼ˆç¹é«”ï¼‰"
  #languageCode = "zh-Hant"
  #languageCodeCountry = "cn"              # custom
  #languageFlag = "ğŸ‡¨ğŸ‡³"                     # custom
  #timeZone = "Asia/Shanghai"
  #tzOffset = "8h"                        # custom
  #tzAbbr = "CST"                          # custom
  #tzAbbrTitle = "China Standard Time"                        # custom
  #weight = 130
  #title = ""
  #[zh-hant.params]
    #description = ""     # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD

#[zh-hans]
#  languageName = "ä¸­æ–‡ï¼ˆç®€ä½“ï¼‰"
#  languageCode = "zh-Hans"
#  languageCodeCountry = "cn"              # custom
#  languageFlag = "ğŸ‡¨ğŸ‡³"                     # custom
#  timeZone = "Asia/Shanghai"
#  tzOffset = "8h"                        # custom
#  tzAbbr = "CST"                          # custom
#  tzAbbrTitle = "China Standard Time"                        # custom
#  weight = 131
#  #title = ""
#  [[zh-hans.menu.main]]
#    identifier = "about"
#    name = "å…³äº"
#    url = "/about/"
#    weight = 2
#  [[zh-hans.menu.main]]
#    identifier = "archives"
#    name = "å½’æ¡£"
#    url = "/archives/"
#    weight = 3

#[ja]
#  languageName = "æ—¥æœ¬èª"
#  languageCode = "ja"
#  languageCodeCountry = "jp"              # custom
#  languageFlag = "ğŸ‡¯ğŸ‡µ"                     # custom
#  timeZone = "Asia/Tokyo"
#  tzOffset = "9h"                        # custom
#  tzAbbr = "JST"                          # custom
#  tzAbbrTitle = "Japan Standard Time"                        # custom
#  weight = 140
#  title = "ãƒã‚¤ãƒ†ã‚¯ ãƒã‚® ğŸš€"
#  [[ja.menu.main]]
#    name              = "ãƒ›ãƒ¼ãƒ "
#    identifier        = "home"
#    url               = "/"
#    pre               = "home"
#    weight            = 1
#    [ja.menu.main.params]
#      newTab = false
#  [ja.params]
#    description = "ç§‘å­¦æŠ€è¡“ã®éŠã³å ´"     # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD

#[ko]
#  languageName = "í•œêµ­ì–´"
#  languageCode = "ko"
#  languageCodeCountry = "kr"              # custom
#  languageFlag = "ğŸ‡°ğŸ‡·"                     # custom
#  timeZone = "Asia/Seoul"
#  tzOffset = "9h"                        # custom
#  tzAbbr = "KST"                          # custom
#  tzAbbrTitle = "Korea Standard Time"                        # custom
#  weight = 150
#  title = "í…Œí¬ ë§ˆêµ¬ìŠ¤ ğŸš€"
#  [[ko.menu.main]]
#    identifier = "about"
#    name = "About"
#    url = "/about/"
#    weight = 2
#  [[ko.menu.main]]
#    identifier = "archives"
#    name = "Archives"
#    url = "/archives/"
#    weight = 3
