# See:  https://gohugo.io/content-management/multilingual/
#       https://gohugo.io/methods/site/language/
#       https://gohugo.io/methods/page/language/
#_merge = "deep"

# lang="{{ or site.Language.LanguageCode site.Language.Lang }}" dir="{{ site.Language.LanguageDirection }}"

### Generic English
[en]                                                # site.Language.Lang
  languageCode = "en"                               # site.Language.LanguageCode
  languageDirection = "ltr"                         # site.Language.LanguageDirection
  languageName = "English"                          # .Site.Language.LanguageName
  #languagePrefix = ""                              # site.Language.LanguagePrefix
  timezone = "Etc/UTC"                              # site.Language.Timezone (??)
  #title = ""                                       # site.Title (site.Language.Title ??)
  weight = 100                                      # site.Language.Weight
  [en.params]                                       # site.Params || site.Params.custom_params
    #languageCodeCountry = ""                       # custom
    languageFlag = "ğŸ‡¬ğŸ‡§"                             # custom
    tzAbbr = "UTC"                                  # custom
    tzAbbrTitle = "Universal Time Coordinated"      # custom
    #tzOffset = "0h"                                # custom
    #description = ""                               # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD
  [[en.menu.main]]
    name = "YOO Station"
    identifier = "yoo-hub"
    url = "https://im.youronly.one/"
    #pre = "<i class='fa fa-home'></i>"
    weight = 1000

### Philippine English
[en-ph]
  languageCode = "en-ph"
  languageDirection = "ltr"
  languageName = "English (PH)"
  #languagePrefix = ""
  timezone = "Asia/Manila"
  #title = ""
  weight = 101
  [en-ph.params]
    languageCodeCountry = "ph"                      # custom
    languageFlag = "ğŸ‡µğŸ‡­"                             # custom
    tzAbbr = "ACT"                                  # custom
    tzAbbrTitle = "Asean Common Time"               # custom
    tzOffset = "8h"                                 # custom
    #description = ""                               # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD
  [[en-ph.menu.main]]
    name = "YOO Station"
    identifier = "yoo-hub"
    url = "https://im.youronly.one/"
    #pre = "<i class='fa fa-home'></i>"
    weight = 1000

### Filipino (áœ‰áœ’áœáœ’áœ‰áœ’áœˆáœ“) in Latin (áœáœ†áœ’áœˆáœ•)
[fil]
  languageCode = "fil"
  languageDirection = "ltr"
  languageName = "Filipino"
  #languagePrefix = ""
  timezone = "Asia/Manila"
  #title = ""
  weight = 200
  [fil.params]
    languageCodeCountry = "ph"                      # custom
    languageFlag = "ğŸ‡µğŸ‡­"                             # custom
    tzAbbr = "ACT"                                  # custom
    tzAbbrTitle = "Asean Common Time"               # custom
    tzOffset = "8h"                                 # custom
    #description = ""                               # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD
  [[fil.menu.main]]
    name = "Himpilang YOO"
    identifier = "yoo-hub"
    url = "https://im.youronly.one/"
    #pre = "<i class='fa fa-home'></i>"
    weight = 1000

### Filipino (áœ‰áœ’áœáœ’áœ‰áœ’áœˆáœ“) in Hangeul (í•œê¸€)
[fil-hang]
  languageCode = "fil-hang"
  languageDirection = "ltr"
  languageName = "í•„ë¦¬í•€ í•œê¸€"
  #languagePrefix = ""
  timezone = "Asia/Manila"
  #title = ""
  weight = 210
  [fil-hang.params]
    languageCodeCountry = "ph"                      # custom
    languageFlag = "ğŸ‡µğŸ‡­"                             # custom
    tzAbbr = "ACT"                                  # custom
    tzAbbrTitle = "Asean Common Time"               # custom
    tzOffset = "8h"                                 # custom
    #description = ""                               # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD
  [[fil-hang.menu.main]]
    name = "í˜í•„ë‘ YOO"
    identifier = "yoo-hub"
    url = "https://im.youronly.one/"
    #pre = "<i class='fa fa-home'></i>"
    weight = 1000

### Tagalog (áœ†áœ„áœáœ“áœ„áœ•) in Baybayin (áœŠáœŒáœ”áœŠáœŒáœ’áœˆáœ•)
[tl-tglg]
  languageCode = "tl-tglg"
  languageDirection = "ltr"
  languageName = "áœŠáœŒáœ”áœŠáœŒáœ’áœˆáœ” áœ†áœ„áœáœ“áœ„áœ•"
  #languagePrefix = ""
  timezone = "Asia/Manila"
  #title = ""
  weight = 300
  [tl-tglg.params]
    languageCodeCountry = "ph"                      # custom
    languageFlag = "ğŸ‡µğŸ‡­"                             # custom
    tzAbbr = "ACT"                                  # custom
    tzAbbrTitle = "Asean Common Time"               # custom
    tzOffset = "8h"                                 # custom
    #description = ""                               # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD
  [[tl-tglg.menu.main]]
    name = "áœ‘áœ’áœ‹áœ”áœ‰áœ’áœáœ…áœ• YOO"
    identifier = "yoo-hub"
    url = "https://im.youronly.one/"
    #pre = "<i class='fa fa-home'></i>"
    weight = 1000

### HÃ nyÇ” (æ¼¢èª) in Traditional HÃ nzÃ¬ (æ¼¢å­—)
[zh-hant]
  languageCode = "zh-hant"
  languageDirection = "ltr"
  languageName = "ä¸­æ–‡ï¼ˆç¹é«”ï¼‰"
  #languagePrefix = ""
  timezone = "Asia/Shanghai"
  #title = ""
  weight = 400
  [zh-hant.params]
    languageCodeCountry = "cn"                      # custom
    languageFlag = "ğŸ‡¨ğŸ‡³"                             # custom
    tzAbbr = "CST"                                  # custom
    tzAbbrTitle = "China Standard Time"             # custom
    tzOffset = "8h"                                 # custom
    #description = ""                               # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD
  [[zh-hant.menu.main]]
    name = "YOOè»Šç«™"
    identifier = "yoo-hub"
    url = "https://im.youronly.one/"
    #pre = "<i class='fa fa-home'></i>"
    weight = 1000

### HÃ nyÇ” (æ±‰è¯­) in Simplified HÃ nzÃ¬ (æ±‰å­—)
[zh-hans]
  languageCode = "zh-hans"
  languageDirection = "ltr"
  languageName = "ä¸­æ–‡ï¼ˆç®€ä½“ï¼‰"
  #languagePrefix = ""
  timezone = "Asia/Shanghai"
  #title = ""
  weight = 401
  [zh-hans.params]
    languageCodeCountry = "cn"                      # custom
    languageFlag = "ğŸ‡¨ğŸ‡³"                             # custom
    tzAbbr = "CST"                                  # custom
    tzAbbrTitle = "China Standard Time"             # custom
    tzOffset = "8h"                                 # custom
    #description = ""                               # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD
  [[zh-hans.menu.main]]
    name = "YOOè½¦ç«™"
    identifier = "yoo-hub"
    url = "https://im.youronly.one/"
    #pre = "<i class='fa fa-home'></i>"
    weight = 1000

### HÃ nyÇ” (æ¼¢èª) in Bopomofo (ã„…ã„†ã„‡ã„ˆ) / Zhuyin (æ³¨éŸ³ / æ³¨éŸ³ç¬¦è™Ÿ)
[zh-bopo]
  languageCode = "zh-bopo"
  languageDirection = "ltr"
  languageName = "Bopomofoï¼ˆã„…ã„†ã„‡ã„ˆï¼‰"
  #languagePrefix = ""
  timezone = "Asia/Shanghai"
  #title = ""
  weight = 402
  [zh-bopo.params]
    languageCodeCountry = "cn"                      # custom
    languageFlag = "ğŸ‡¨ğŸ‡³"                             # custom
    tzAbbr = "CST"                                  # custom
    tzAbbrTitle = "China Standard Time"             # custom
    tzOffset = "8h"                                 # custom
    #description = ""                               # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD
  [[zh-bopo.menu.main]]
    name = "YOOè»Šç«™"
    identifier = "yoo-hub"
    url = "https://im.youronly.one/"
    #pre = "<i class='fa fa-home'></i>"
    weight = 1000

### Nihongo (æ—¥æœ¬èª (ã«ã»ã‚“ã”)) in Kana (ä»®å (ã‹ãª))
[ja]
  languageCode = "ja"
  languageDirection = "ltr"
  languageName = "æ—¥æœ¬èª"
  #languagePrefix = ""
  timezone = "Asia/Tokyo"
  #title = ""
  weight = 500
  [ja.params]
    languageCodeCountry = "jp"                      # custom
    languageFlag = "ğŸ‡¯ğŸ‡µ"                             # custom
    tzAbbr = "JST"                                  # custom
    tzAbbrTitle = "Japan Standard Time"             # custom
    tzOffset = "9h"                                 # custom
    #description = ""                               # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD
  [[ja.menu.main]]
    name = "YOOã‚¹ãƒ†ãƒ¼ã‚·ãƒ§ãƒ³"
    identifier = "yoo-hub"
    url = "https://im.youronly.one/"
    #pre = "<i class='fa fa-home'></i>"
    weight = 1000

### Hangugeo (í•œêµ­ì–´) in Hangeul (í•œê¸€)
[ko]
  languageCode = "ko"
  languageDirection = "ltr"
  languageName = "í•œêµ­ì–´"
  #languagePrefix = ""
  timezone = "Asia/Seoul"
  #title = ""
  weight = 600
  [ko.params]
    languageCodeCountry = "kr"                      # custom
    languageFlag = "ğŸ‡°ğŸ‡·"                             # custom
    tzAbbr = "KST"                                  # custom
    tzAbbrTitle = "Korea Standard Time"             # custom
    tzOffset = "9h"                                 # custom
    #description = ""                               # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD
  [[ko.menu.main]]
    name = "YOO ìŠ¤í…Œì´ì…˜"
    identifier = "yoo-hub"
    url = "https://im.youronly.one/"
    #pre = "<i class='fa fa-home'></i>"
    weight = 1000

###
